// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owjesarxaebpdydsuxsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93amVzYXJ4YWVicGR5ZHN1eHNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTcwMDMsImV4cCI6MjA2OTI5MzAwM30.zlU423GUWkKSnrAuw_nPtcBohmjSTXPMhNIzsgRGV6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});